### ISSUE TITLE
invalid conversion

### ISSUE THREAD

**Issue by PA4WD** [guglicap/arduino-pv#1]
i get the error "invalid conversion from 'uint16_t {aka short unsigned int}' to 'char*' [-fpermissive]"
when compiling for esp8266 
file protocol.cpp 
```
uint16_t value = *(data++) << 8 | `*(data++);`
status[x] = StatusElem{value, name};
```
value in StatusElem gives the error.

**Comment by guglicap** [comment]
Uh, yeah, that's a stupid bug I remember. Glad to see someone looking for this library, I had temporarily (for half a year, actually) abandoned the project, but I was about to pick it up again as I now have a lot more free time. Contact me if you wouldn't mind helping me with it, please. It might also mean only testing it on another setup, that would still help. I'll make a commit right now that should fix the issue.

**Comment by PA4WD** [comment]
thanks.
I am making a datalogger for a sunezy 2800. Reading serial and convert to json. Then post it to a influxdb and making graphs with grafana. As hardware i am using a simple nodemcu board.
Is there example code to get started?

**Comment by guglicap** [comment]
I added an example which gets the inverter status. 
Right now, the library API isn't very user friendly though, and I plan on rewriting it. 
Also everything is undocumented but the API calls all work similarly (you pass a buffer which gets filled and the function returns the length of the response). 
You can read the source code for the other functions, it's not very complicated, specifically `inverter.h` and `status.h`. 
Let me know.
